# -*- coding: utf-8 -*-
"""data_fusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8Drngjc3692SzqcRXV-vepFRUPa55dE
"""

import pandas as pd

iot = pd.read_csv("ai4i2020.csv")
weather = pd.read_csv("weather_forecast_data.csv")

print(iot.head())
print(weather.head())

print(iot.columns)
print(weather.columns)

import pandas as pd

iot['timestamp'] = pd.date_range(
    start='2024-01-01',
    periods=len(iot),
    freq='H'
)

print(iot.head())

print(weather.head())

weather['timestamp'] = pd.date_range(
    start='2024-01-01',
    periods=len(weather),
    freq='h'
)
print(weather.head())

merged = pd.merge_asof(
    iot.sort_values('timestamp'),
    weather.sort_values('timestamp'),
    on='timestamp',
    direction='nearest'
)

print(merged.head())

merged['temp_diff'] = merged['Air temperature [K]'] - merged['Process temperature [K]']

merged['power'] = merged['Torque [Nm]'] * merged['Rotational speed [rpm]']

print(merged['Machine failure'].value_counts())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X = merged.select_dtypes(include='number').drop(columns=['Machine failure'])
y = merged['Machine failure']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train)

print("Accuracy:", model.score(X_test, y_test))

merged.to_csv("final_fused_dataset.csv", index=False)

from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt

importances = model.feature_importances_
features = X.columns

plt.barh(features, importances)
plt.xlabel("Importance")
plt.ylabel("Features")
plt.title("Feature Importance")
plt.show()

X_basic = iot.select_dtypes(include='number').drop(columns=['Machine failure'])
y_basic = iot['Machine failure']

X_train, X_test, y_train, y_test = train_test_split(X_basic, y_basic, test_size=0.2)

model_basic = RandomForestClassifier()
model_basic.fit(X_train, y_train)

print("Accuracy without fusion:", model_basic.score(X_test, y_test))

X = merged.select_dtypes(include='number').drop(columns=['Machine failure'])
y = merged['Machine failure']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("Accuracy with fusion:", model.score(X_test, y_test))

X = merged.select_dtypes(include='number')

X = merged.select_dtypes(include='number').drop(columns=['Machine failure'])
y = merged['Machine failure']

from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

print(X.columns)

X = merged.select_dtypes(include='number').drop(columns=['Machine failure'])
y = merged['Machine failure']

from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))

print(merged['Machine failure'].value_counts())

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

